# Generated by Django 4.1.7 on 2023-03-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0004_rename_settings_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_box_art',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_icon',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_ingame',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='image_title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
