# Generated by Django 4.1.7 on 2023-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0006_achievement'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerscore',
            name='raw_score',
            field=models.IntegerField(default=0),
        ),
    ]
